### PR TITLE
Contribution.md

### PR DESCRIPTION
**Pull request by akshitac8**
Added Contribution.md for newcomers to get started on the Diversity Repo.
This issue is in reference to the issue #170  :smiley: 
@emmairwin It would be great if you could share your views on this one.

### CODE REVIEW

**Comment by emmairwin** [comment]
Hi Akshita!

Thanks for this, can you please change the file name to CONTRIBUTION.md as is the standard (from CONTRIBUTION.md) 

Thankyou!

**Comment by akshitac8** [comment]
Done :)

**Comment by akshitac8** [comment]
@emmairwin Should we merge the PR? :smiley:

**Review by corongan — COMMENTED** [review]
👏🏼

**Comment by Bobbyy44** [comment]
akshitac8:contributing

**Pull request merged**
